-- ChurnSense shared database setup for Supabase PostgreSQL.
-- Run this whole file once in Supabase Dashboard -> SQL Editor.

-- ============================================================
-- 1) SHARED TABLES
-- ============================================================

-- Store application profile fields and the RBAC role.
create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    name text not null default '',
    email text not null unique,
    organization text not null default '',
    job_title text not null default '',
    role text not null default 'user' check (role in ('user', 'analyst', 'manager', 'admin')),
    created_at timestamptz not null default now()
);

-- Store each user's interface preferences.
create table if not exists public.user_settings (
    user_id uuid primary key references public.profiles(id) on delete cascade,
    language text not null default 'en' check (language in ('en', 'ar')),
    theme text not null default 'light' check (theme in ('light', 'dark')),
    email_notifications boolean not null default false,
    updated_at timestamptz not null default now()
);

-- Store shared prediction history.
create table if not exists public.predictions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    customer_reference text not null default '',
    customer_data jsonb not null,
    probability double precision not null check (probability >= 0 and probability <= 1),
    prediction text not null check (prediction in ('Yes', 'No')),
    created_at timestamptz not null default now()
);

-- Keep user history queries fast.
create index if not exists idx_predictions_user_created
on public.predictions (user_id, created_at desc);


-- ============================================================
-- 2) AUTOMATIC PROFILE CREATION AFTER SIGN-UP
-- ============================================================

-- Create the ChurnSense profile and default settings whenever Supabase Auth creates a user.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.profiles (id, name, email, role)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'name', ''),
        lower(coalesce(new.email, '')),
        'user'
    )
    on conflict (id) do nothing;

    insert into public.user_settings (user_id)
    values (new.id)
    on conflict (user_id) do nothing;

    return new;
end;
$$;

-- Recreate the trigger safely if this setup file is run again.
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_auth_user();


-- ============================================================
-- 3) ROW LEVEL SECURITY (RLS)
-- ============================================================

-- Turn RLS on for every table exposed through the Data API.
alter table public.profiles enable row level security;
alter table public.user_settings enable row level security;
alter table public.predictions enable row level security;

-- A normal signed-in user can read only their own profile.
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (id = auth.uid());

-- A normal signed-in user can read only their own settings.
drop policy if exists "settings_select_own" on public.user_settings;
create policy "settings_select_own"
on public.user_settings
for select
to authenticated
using (user_id = auth.uid());

-- A normal signed-in user can create only their own settings row.
drop policy if exists "settings_insert_own" on public.user_settings;
create policy "settings_insert_own"
on public.user_settings
for insert
to authenticated
with check (user_id = auth.uid());

-- A normal signed-in user can update only their own settings row.
drop policy if exists "settings_update_own" on public.user_settings;
create policy "settings_update_own"
on public.user_settings
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- A normal signed-in user can read only predictions created by their account.
drop policy if exists "predictions_select_own" on public.predictions;
create policy "predictions_select_own"
on public.predictions
for select
to authenticated
using (user_id = auth.uid());

-- A normal signed-in user can save predictions only under their own account.
drop policy if exists "predictions_insert_own" on public.predictions;
create policy "predictions_insert_own"
on public.predictions
for insert
to authenticated
with check (user_id = auth.uid());


-- ============================================================
-- 4) SAFE PROFILE UPDATE FUNCTION
-- ============================================================

-- Update only editable profile fields; the caller cannot change their own role here.
create or replace function public.update_my_profile(
    p_name text,
    p_organization text,
    p_job_title text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    if auth.uid() is null then
        raise exception 'Authentication required';
    end if;

    update public.profiles
    set
        name = trim(coalesce(p_name, '')),
        organization = trim(coalesce(p_organization, '')),
        job_title = trim(coalesce(p_job_title, ''))
    where id = auth.uid();
end;
$$;


-- ============================================================
-- 5) ROLE / ADMIN HELPERS
-- ============================================================

-- Check the live shared role of the signed-in account.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and role = 'admin'
    );
$$;

-- Return one user's own dashboard totals.
create or replace function public.my_dashboard_summary()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
    select jsonb_build_object(
        'total', count(*),
        'high_risk', count(*) filter (where prediction = 'Yes'),
        'average_probability', coalesce(avg(probability), 0)
    )
    from public.predictions
    where user_id = auth.uid();
$$;

-- Let an admin list safe application profile fields for all shared users.
create or replace function public.admin_list_users()
returns table (
    id uuid,
    name text,
    email text,
    organization text,
    job_title text,
    role text,
    created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
    if not public.is_admin() then
        raise exception 'Admin access required';
    end if;

    return query
    select
        p.id,
        p.name,
        p.email,
        p.organization,
        p.job_title,
        p.role,
        p.created_at
    from public.profiles p
    order by p.created_at desc;
end;
$$;

-- Let an admin change another user's role while blocking accidental self-demotion.
create or replace function public.admin_update_user_role(
    p_user_id uuid,
    p_new_role text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
    if not public.is_admin() then
        raise exception 'Admin access required';
    end if;

    if p_new_role not in ('user', 'analyst', 'manager', 'admin') then
        raise exception 'Invalid role';
    end if;

    if p_user_id = auth.uid() and p_new_role <> 'admin' then
        raise exception 'You cannot remove your own admin role';
    end if;

    if not exists (select 1 from public.profiles where id = p_user_id) then
        raise exception 'User not found';
    end if;

    update public.profiles
    set role = p_new_role
    where id = p_user_id;

    return jsonb_build_object(
        'user_id', p_user_id,
        'role', p_new_role
    );
end;
$$;

-- Return shared workspace totals to admins only.
create or replace function public.admin_summary()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    result jsonb;
begin
    if not public.is_admin() then
        raise exception 'Admin access required';
    end if;

    select jsonb_build_object(
        'users', (select count(*) from public.profiles),
        'predictions', (select count(*) from public.predictions)
    ) into result;

    return result;
end;
$$;


-- ============================================================
-- 6) DATA API PRIVILEGES
-- ============================================================

-- Remove anonymous table access.
revoke all on table public.profiles from anon;
revoke all on table public.user_settings from anon;
revoke all on table public.predictions from anon;

-- Give signed-in users only the direct table privileges the app needs.
grant select on table public.profiles to authenticated;
grant select, insert, update on table public.user_settings to authenticated;
grant select, insert on table public.predictions to authenticated;

-- Allow signed-in users to call the protected helper functions.
grant execute on function public.update_my_profile(text, text, text) to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.my_dashboard_summary() to authenticated;
grant execute on function public.admin_list_users() to authenticated;
grant execute on function public.admin_update_user_role(uuid, text) to authenticated;
grant execute on function public.admin_summary() to authenticated;

-- Keep privileged functions unavailable to anonymous visitors.
revoke execute on function public.update_my_profile(text, text, text) from anon;
revoke execute on function public.is_admin() from anon;
revoke execute on function public.my_dashboard_summary() from anon;
revoke execute on function public.admin_list_users() from anon;
revoke execute on function public.admin_update_user_role(uuid, text) from anon;
revoke execute on function public.admin_summary() from anon;
